### ISSUE TITLE
大神，怎么用宝塔安装啊，我急需

### ISSUE THREAD

**Issue by 2463091804** [52admln/vue-questionnaire#25]

**Comment by 52admln** [comment]
前端文件打包出来后，把 dist 下的文件丢到网站根目录，然后把仓库下的 `api` 文件夹也放到根目录。把 `api/application/config/database.php` 里面数据库信息修改好，数据库导入 `api/database.sql` 文件。

环境需要 Apache + PHP 5.6以上 + MySQL。

**Comment by 2463091804** [comment]
还是不咋会，原谅我，可以的话大神把宝塔搭建的教程说详细些，小弟愿意打赏，谢谢~

**Comment by 52admln** [comment]
QQ方便私聊吗? 148103797

**Comment by 2463091804** [comment]
> QQ方便私聊吗？148103797

暂时不方便，我在上班，晚点可以~

**Comment by 2463091804** [comment]
> 前端文件打包出来后，把dist下的文件丢到网站根目录，然后把仓库下的`api`文件夹也放到根目录。把`api/application/config/database.php`里面数据库信息修改好，数据库导入`api/database.sql`文件。
> 
> 环境需要Apache + PHP 5.6以上+ MySQL。
