### ISSUE TITLE
不能编辑修改问卷的问题

### ISSUE THREAD

**Issue by shaukei** [52admln/vue-questionnaire#41]
打算支持发布前修改问卷吗？不支持的话，有点坑呢！

**Comment by 52admln** [comment]
这个功能后面会加，等有空的时候补上。

shaukei <notifications@github.com> 于2019年7月16日周二 上午11:30写道：

**Comment by 52admln** [comment]
此功能已更新到 TypeScript 版本，可参看 `README.md`
